= Terms of Use

This Extension is subject to the terms of your Main Services Agreement with Salesforce. 

If you do not have a Main Services Agreement in place with Salesforce, by downloading this Extension you agree to the terms of the Main Services Agreement (the “Agreement”) found https://www.salesforce.com/en-us/wp-content/uploads/sites/4/documents/legal/Salesforce_MSA.pdf[here] and acknowledge that if you are accepting this Agreement on behalf of a company or other legal entity, you have the authority to bind such entity and affiliates to the Agreement. 

This Extension may include some services that are in beta. These beta services are subject to the Beta Services Terms at https://www.salesforce.com/company/legal/agreements/[Agreements - Salesforce.com] or a written Unified Pilot Agreement if executed by Customer, and applicable terms in the https://ptd.salesforce.com/?_ga=2.247987783.1372150065.1709219475-629000709.1639001992[Product Terms Directory]. Use of any beta services is at the Customer's sole discretion.

Generative AI can produce inaccurate or harmful responses. Review the output for accuracy and safety. You assume responsibility for how the outcomes are applied to your organization.
